---
name: Release and publish to Ansible Galaxy
on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: daixijun.grafana_agent

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: daixijun.grafana_agent

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
          architecture: x64
          cache: pip

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Publish role to Galaxy
        run: ansible-galaxy role import --branch main --api-key ${{ secrets.ANSIBLE_GALAXY_API_KEY }} $(echo $GITHUB_REPOSITORY | cut -d/ -f1) $(echo $GITHUB_REPOSITORY | cut -d/ -f2)
